### ISSUE TITLE
Need to implement ResilientEventHubSender

### ISSUE THREAD

**Issue by rtandonmsft** [hdinsight/eventhubs-client#2]
Today the EventHubSender throws if a known exception occurred and just logs if an unknown exception occurred.

This logic should be reworked to have a better retry-able strategy and recovery of the connection.

This issue immediately impacts the EventHubs-Bolt in Storm wherein the Bolt just keeps logging the exception, so neither the sender recovers or the bolt recovers.

Cheaper fix is in Bolt to crash when this happens, but its much better to think of a resiliency story here.

**Comment by codebrewer** [comment]
I'd like to see this too (or see a checked exception thrown so my code can take some action).  As it stands the current implementation gives no indication that anything is wrong (aside from logging a message).

**Comment by rtandonmsft** [comment]
https://github.com/hdinsight/eventhubs-client/commit/59d7e6630c1c19a94de94469383a73b7c1979cd8

Instead of adding another class, I improved the error handling in EventHubSender that will send better information and throw on errors where the connection needs to be re-established.

@codebrewer Please try it out and let me know if there are any issues you see.
I have been running the [Storm Event Hub Sender Topology] (https://github.com/hdinsight/hdinsight-storm-examples/blob/master/RealTimeETLExample/EventHubAggregatorToHBaseTopology/EventHubAggregatorToHBaseTopology.cs#L24) for 3 days which has showed great results.

Earlier I used to see the silent error in about 24 hours, and now its 72 hours, and I see 0 failed events as the error was rightly handled.

```
2015-09-28 08:32:16 c.m.e.c.EventHubSender [ERROR] null
2015-09-28 08:32:16 b.s.d.executor [ERROR] 
com.microsoft.eventhubs.client.EventHubException: Sender has been closed.
	at com.microsoft.eventhubs.client.EventHubSender.HandleException(EventHubSender.java:88) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.client.EventHubSender.send(EventHubSender.java:70) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.bolt.EventHubBolt.execute(EventHubBolt.java:86) ~[stormjar.jar:na]
	at backtype.storm.daemon.executor$fn__5132$tuple_action_fn__5134.invoke(executor.clj:659) [storm-core-0.9.3.2.2.7.1-0004.jar:0.9.3.2.2.7.1-0004]
	at backtype.storm.daemon.executor$mk_task_receiver$fn__5055.invoke(executor.clj:415) [storm-core-0.9.3.2.2.7.1-0004.jar:0.9.3.2.2.7.1-0004]
	at backtype.storm.disruptor$clojure_handler$reify__3090.onEvent(disruptor.clj:58) [storm-core-0.9.3.2.2.7.1-0004.jar:0.9.3.2.2.7.1-0004]
	at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:125) [storm-core-0.9.3.2.2.7.1-0004.jar:0.9.3.2.2.7.1-0004]
	at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:99) [storm-core-0.9.3.2.2.7.1-0004.jar:0.9.3.2.2.7.1-0004]
	at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80) [storm-core-0.9.3.2.2.7.1-0004.jar:0.9.3.2.2.7.1-0004]
	at backtype.storm.daemon.executor$fn__5132$fn__5145$fn__5196.invoke(executor.clj:794) [storm-core-0.9.3.2.2.7.1-0004.jar:0.9.3.2.2.7.1-0004]
	at backtype.storm.util$async_loop$fn__550.invoke(util.clj:465) [storm-core-0.9.3.2.2.7.1-0004.jar:0.9.3.2.2.7.1-0004]
	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_55]
Caused by: org.apache.qpid.amqp_1_0.client.LinkDetachedException: null
	at org.apache.qpid.amqp_1_0.client.Sender.send(Sender.java:336) ~[stormjar.jar:na]
	at org.apache.qpid.amqp_1_0.client.Sender.send(Sender.java:251) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.client.EventHubSender.send(EventHubSender.java:67) ~[stormjar.jar:na]
	... 11 common frames omitted
2015-09-28 08:32:16 c.m.e.c.EventHubSender [INFO] Creating EventHubs sender
```

FYI @shanyu @ashitgosalia
