### ISSUE TITLE
Having large messages (100-240KB) in EventHubs may cause receive failure.

### ISSUE THREAD

**Issue by rtandonmsft** [hdinsight/eventhubs-client#3]
There is a problem in the qpid-amqp client library when handling multi-chunk messages. Due to this bug the message may not be assembled correctly and that could result in receive hang or null point exception in message decoding.

If you had small messages (<64KB), it would not happen because the message can be sent in one frame. When you have more large messages (I have seen a few 100-200KB ones in my test), the chance to hit this bug would be higher.

The fix for this needs to be done in qpid-amqp jar.

Some call stacks from Storm spout using this client:
2015-07-13 13:00:59 b.s.util [ERROR] Async loop died!
java.lang.RuntimeException: Error{condition=detach-forced,description=The link 'G18:3561300:eventhubs-receiver-link' is force detached by the broker due to errors occurred in

2015-07-13 13:00:59 c.m.e.c.EventHubReceiver [ERROR] Error{condition=detach-forced,description=The link 'G18:3561300:eventhubs-receiver-link' is force detached by the broker due to errors occurred in consumer(link398864). Detach origin: AmqpMessageConsumer.IdleTimerExpired: Idle timeout: 00:10:00. TrackingId:<redacted>,TimeStamp:7/13/2015 1:00:59 PM}
2015-07-13 13:00:59 b.s.util [ERROR] Async loop died!
java.lang.RuntimeException: Error{condition=detach-forced,description=The link 'G18:3561300:eventhubs-receiver-link' is force detached by the broker due to errors occurred in consumer(link398864). Detach origin: AmqpMessageConsumer.IdleTimerExpired: Idle timeout: 00:10:00. TrackingId:<redacted>,TimeStamp:7/13/2015 1:00:59 PM}
       at com.microsoft.eventhubs.client.EventHubReceiver.checkError(EventHubReceiver.java:123) ~[stormjar.jar:na]
       at com.microsoft.eventhubs.client.EventHubReceiver.receive(EventHubReceiver.java:86) ~[stormjar.jar:na]
       at com.microsoft.eventhubs.spout.EventHubReceiverImpl.receive(EventHubReceiverImpl.java:111) ~[stormjar.jar:na]
       at com.microsoft.eventhubs.spout.PartitionManager.receive(PartitionManager.java:56) ~[stormjar.jar:na]
       at com.microsoft.eventhubs.spout.EventHubSpout.nextTuple(EventHubSpout.java:187) ~[stormjar.jar:na]

2015-07-14 15:30:26 c.m.e.c.EventHubReceiver [ERROR] Error{condition=detach-forced,description=The link 'G18:5139234:eventhubs-receiver-link' is force detached by the broker due to errors occurred in consumer(link247017). Detach origin: AmqpMessageConsumer.IdleTimerExpired: Idle timeout: 00:10:00. TrackingId:<redacted>,TimeStamp:7/14/2015 3:30:26 PM}
2015-07-14 15:30:26 b.s.util [ERROR] Async loop died!
java.lang.RuntimeException: Error{condition=detach-forced,description=The link 'G18:5139234:eventhubs-receiver-link' is force detached by the broker due to errors occurred in consumer(link247017). Detach origin: AmqpMessageConsumer.IdleTimerExpired: Idle timeout: 00:10:00. TrackingId:<redacted>,TimeStamp:7/14/2015 3:30:26 PM}
       at com.microsoft.eventhubs.client.EventHubReceiver.checkError(EventHubReceiver.java:123) ~[stormjar.jar:na]
       at com.microsoft.eventhubs.client.EventHubReceiver.receive(EventHubReceiver.java:86) ~[stormjar.jar:na]
       at com.microsoft.eventhubs.spout.EventHubReceiverImpl.receive(EventHubReceiverImpl.java:111) ~[stormjar.jar:na]
       at com.microsoft.eventhubs.spout.PartitionManager.receive(PartitionManager.java:56) ~[stormjar.jar:na]
       at com.microsoft.eventhubs.spout.EventHubSpout.nextTuple(EventHubSpout.java:187) ~[stormjar.jar:na]

**Comment by akeninovex** [comment]
I'm not sure if I am hitting this issue, but I encounter NPEs as described in the following JIRA for messages around 100-150KB: 
https://issues.apache.org/jira/browse/QPID-6482
But not always: the behaviour is indeterminate and can be avoided by introducing a sleep into the EventHub spout (which of course makes no sense in a real-time infrastructure).

**Comment by rtandonmsft** [comment]
Closing this issue, since any bugs or new asks should land here: https://github.com/Azure/azure-event-hubs

There is a private variation of qpid library available with a fix for this, but instead of pursuing that, its better to switch to newer Proton-J based library.
